export const SET_BUDGET_TITLE = 'SET_BUDGET_TITLE'
export const SET_INITIAL_BUDGET = 'SET_INITIAL_BUDGET'
export const SET_BUDGET_DEADLINE= 'SET_BUDGET_DEADLINE'
export const SET_COMPLETE_STATE= 'SET_COMPLETE_STATE'